### PR TITLE
Changes done to intergrate knn algorithm.

### PR DESCRIPTION
**Pull request by belkarteur**
file knn_features_geusser added

### CODE REVIEW

**Review by belkarteur — COMMENTED** [review]
check

**Comment by harmakit** [comment]
but.. the idea was to get rid of 
```
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
```

in https://github.com/harmakit/digit-recognition/blob/main/service/guesser_factory.py 
and pass self-written methods in `self.feature_methods_classifiers`

**Comment by belkarteur** [comment]
I am not using any library. Probably I wrote the code in the wrong classes.
Okay I will check it and correct.

**Comment by harmakit** [comment]
done in https://github.com/harmakit/digit-recognition/commit/33c456fdb1fc902edac2a572f4824ea75b5f8868

**Pull request closed without merging**
